const { useMemo, useState } = React;
const API_BASE_URL = "https://CheckMate-AI.onrender.com";

function App() {
  const [aiOutput, setAiOutput] = useState("");
  const [prompt, setPrompt] = useState("");
  const [isLoading, setIsLoading] = useState(false);
  const [isDragOver, setIsDragOver] = useState(false);
  const [results, setResults] = useState(null);
  const [apiMessage, setApiMessage] = useState("");

  const highlightKeywords = ["always", "never", "guaranteed", "everyone", "proven"];

  const colorFromScore = (score) => {
    if (score >= 70) return { text: "risk-red", bg: "bg-red", label: "High Risk" };
    if (score >= 40) return { text: "risk-orange", bg: "bg-orange", label: "Medium Risk" };
    return { text: "risk-green", bg: "bg-green", label: "Good" };
  };

  const detectRisk = (text, base) => {
    const lower = text.toLowerCase();
    const keywordHits = highlightKeywords.filter((word) => lower.includes(word)).length;
    const lengthPenalty = text.length > 450 ? 12 : 0;
    const score = Math.min(95, base + keywordHits * 9 + lengthPenalty);
    return score;
  };

  const buildLocalResult = () => {
    const biasScore = detectRisk(aiOutput, 32);
    const hallucinationScore = detectRisk(aiOutput + prompt, 28);
    const promptScore = detectRisk(prompt, 22);
    const total = Math.round((biasScore + hallucinationScore + promptScore) / 3);

    return {
      bias: {
        score: biasScore,
        explanation: "The response uses broad statements that may overgeneralize groups or outcomes.",
        fix: "Use neutral words, avoid all-or-nothing claims, and add balanced context.",
      },
      hallucination: {
        score: hallucinationScore,
        source: "Wikipedia cross-check: related summary found but some details are unsupported.",
        fix: "Verify facts with trusted citations before finalizing the output text.",
      },
      promptRisk: {
        score: promptScore,
        suggestion:
          "Suggested prompt: 'Give a balanced answer with factual references, confidence level, and possible limitations.'",
        fix: "Add clearer constraints: ask for sources, confidence score, and avoid assumptions.",
      },
      total,
      topIssues: [
        "High-certainty language without evidence",
        "Potentially unsupported factual claim",
        "Prompt lacks verification requirement",
      ],
    };
  };

  const analyzeText = async () => {
    if (!aiOutput.trim() || !prompt.trim()) {
      alert("Please fill both text areas before analyzing.");
      return;
    }

    setIsLoading(true);
    setApiMessage("");

    try {
      const response = await fetch(`${API_BASE_URL}/analyze`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          ai_output: aiOutput,
          original_prompt: prompt,
        }),
      });

      if (!response.ok) {
        throw new Error("Server returned an error response.");
      }

      const data = await response.json();
      setResults(data);
      setApiMessage("Results generated by backend.");
    } catch (error) {
      const generated = buildLocalResult();
      setResults(generated);
      setApiMessage("Backend not reachable. Showing local demo analysis.");
    } finally {
      // Keep a short loading moment so UI remains consistent for demo.
      await new Promise((resolve) => setTimeout(resolve, 2000));
      setIsLoading(false);
    }
  };

  const copyText = async (text) => {
    try {
      await navigator.clipboard.writeText(text);
      alert("Copied to clipboard.");
    } catch (error) {
      alert("Copy failed. Please copy manually.");
    }
  };

  const exportPdf = () => {
    window.print();
  };

  const saveLocal = () => {
    if (!results) {
      alert("Run ANALYZE first.");
      return;
    }
    localStorage.setItem("checkmate-last-analysis", JSON.stringify({ aiOutput, prompt, results }));
    alert("Saved locally in browser.");
  };

  const onDropFile = (event) => {
    event.preventDefault();
    setIsDragOver(false);
    const file = event.dataTransfer.files[0];
    if (!file) return;
    const reader = new FileReader();
    reader.onload = (e) => {
      setAiOutput(String(e.target.result || ""));
    };
    reader.readAsText(file);
  };

  const highlightedPreview = useMemo(() => {
    const source = aiOutput || "Your highlighted risky phrases will appear here after typing.";
    const chunks = source.split(/\s+/).slice(0, 80);
    return chunks.map((word, idx) => {
      const clean = word.toLowerCase().replace(/[^\w]/g, "");
      const flagged = highlightKeywords.includes(clean);
      return (
        <span key={`${word}-${idx}`} className={flagged ? "snippet" : ""}>
          {word}{" "}
        </span>
      );
    });
  }, [aiOutput]);

  return (
    <main className="app">
      <section className="section-card">
        <h1>♛ CheckMate</h1>
        <p className="hero-subtitle">
          Bias & Hallucination Detection Tool
        </p>
      </section>

      <section className="section-card">
        <h2>Input Section</h2>
        <div className="grid-2">
          <div className="field-group">
            <label htmlFor="ai-output">AI Generated Output</label>
            <textarea
              id="ai-output"
              placeholder="Paste AI response here..."
              value={aiOutput}
              onChange={(e) => setAiOutput(e.target.value)}
            />
          </div>
          <div className="field-group">
            <label htmlFor="prompt">Original Prompt</label>
            <textarea
              id="prompt"
              placeholder="Paste your original prompt here..."
              value={prompt}
              onChange={(e) => setPrompt(e.target.value)}
            />
          </div>
        </div>

        <div
          className={`drop-zone ${isDragOver ? "active" : ""}`}
          onDragOver={(e) => {
            e.preventDefault();
            setIsDragOver(true);
          }}
          onDragLeave={() => setIsDragOver(false)}
          onDrop={onDropFile}
          title="Drop a .txt file to load AI output quickly"
        >
          <strong>Drag & Drop Upload</strong>
          <p>Drop text file here to auto-fill AI Generated Output.</p>
        </div>

        <button className="btn btn-main" onClick={analyzeText} disabled={isLoading}>
          {isLoading ? "Analyzing..." : "ANALYZE"}
        </button>

        {isLoading && (
          <div className="loading-wrap">
            <div className="spinner"></div>
            <span>Running checks... this takes about 2 seconds.</span>
          </div>
        )}

        {apiMessage && (
          <p style={{ marginTop: "12px", color: "#3f5f87", fontWeight: "600" }}>{apiMessage}</p>
        )}
      </section>

      <section className="section-card">
        <h2>Analysis Results</h2>
        {results ? (
          <div className="cards">
            <ResultCard
              icon="🚨"
              title="Bias Detection"
              score={results.bias.score}
              explanation={results.bias.explanation}
              fix={results.bias.fix}
              colorFromScore={colorFromScore}
              copyText={copyText}
              tooltip="Checks language for stereotyping or overgeneralization"
            />
            <ResultCard
              icon="❌"
              title="Hallucination Check"
              score={results.hallucination.score}
              explanation={results.hallucination.source}
              fix={results.hallucination.fix}
              colorFromScore={colorFromScore}
              copyText={copyText}
              tooltip="Compares response confidence against known references"
            />
            <ResultCard
              icon="⚠"
              title="Prompt Risk Analysis"
              score={results.promptRisk.score}
              explanation={results.promptRisk.suggestion}
              fix={results.promptRisk.fix}
              colorFromScore={colorFromScore}
              copyText={copyText}
              tooltip="Checks whether your prompt can cause unsafe/unclear output"
            />
          </div>
        ) : (
          <p>Run ANALYZE to see score cards, fixes, and suggestions.</p>
        )}
      </section>

      <section className="section-card">
        <h2>Overall Summary</h2>
        {results ? (
          <div className="summary-grid">
            <div>
              <h3>Total Score Breakdown</h3>
              <div style={{ marginTop: "10px" }}>
                <span className="score-pill">Bias: {results.bias.score}/100</span>
                <span className="score-pill">Hallucination: {results.hallucination.score}/100</span>
                <span className="score-pill">Prompt Risk: {results.promptRisk.score}/100</span>
                <span className="score-pill">Overall: {results.total}/100</span>
              </div>

              <div className="stack-gap" style={{ marginTop: "18px" }}>
                <h3>Top 3 Issues (Highlighted Text)</h3>
                <ol className="issue-list">
                  {results.topIssues.map((issue) => (
                    <li key={issue}>{issue}</li>
                  ))}
                </ol>
                <div title="Keyword highlighting preview from AI output">
                  <span className="tooltip">Highlighted text preview:</span>
                  <p>{highlightedPreview}</p>
                </div>
              </div>
            </div>

            <div>
              <h3>Quick Fixes</h3>
              <p style={{ color: "#5a7697" }}>
                Copy all fixes, export as PDF, or save your current analysis.
              </p>
              <div className="action-row">
                <button
                  className="btn btn-ghost"
                  onClick={() =>
                    copyText(
                      [
                        `Bias Fix: ${results.bias.fix}`,
                        `Hallucination Fix: ${results.hallucination.fix}`,
                        `Prompt Fix: ${results.promptRisk.fix}`,
                      ].join("\n")
                    )
                  }
                >
                  Copy All
                </button>
                <button className="btn btn-ghost" onClick={exportPdf}>
                  Export PDF
                </button>
                <button className="btn btn-danger" onClick={saveLocal}>
                  Save
                </button>
              </div>
            </div>
          </div>
        ) : (
          <p>No summary yet. Add content and click ANALYZE.</p>
        )}
      </section>

      <footer>Designed and Developed By CodeThinkers | © all rights reserved</footer>
    </main>
  );
}

function ResultCard({ icon, title, score, explanation, fix, colorFromScore, copyText, tooltip }) {
  const color = colorFromScore(score);
  return (
    <article className="result-card">
      <div className="card-top">
        <h3>
          {icon} {title}
        </h3>
        <span className={`risk-label ${color.text}`} title={tooltip}>
          {score}/100 - {color.label}
        </span>
      </div>
      <div className="bar-wrap">
        <div className={`bar-fill ${color.bg}`} style={{ width: `${score}%` }}></div>
      </div>
      <p>{explanation}</p>
      <p>
        <strong>Fix:</strong> {fix}
      </p>
      <button className="btn btn-ghost" onClick={() => copyText(fix)}>
        COPY FIX
      </button>
    </article>
  );
}

ReactDOM.createRoot(document.getElementById("root")).render(<App />);
